[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Root = Split-Path -Parent $PSScriptRoot
$ServerDir = Join-Path $Root 'server'
$ModsDir = Join-Path $ServerDir 'mods'
$ManifestPath = Join-Path $ServerDir 'mods-manifest.ps1'
$FabricInstaller = Join-Path $ServerDir 'fabric-installer-1.1.2.jar'
$FabricInstallerUrl = 'https://maven.fabricmc.net/net/fabricmc/fabric-installer/1.1.2/fabric-installer-1.1.2.jar'
$FabricInstallerSha512 = '3cbe7b69498c44d814fc95e71cd9ce9c12c45a9e1dcf01085cb3e9aaf6fe63134b701065167be1fa6e4c2df19dfa5400bc5b6b1b7fb5e99e334d24dcdca55c20'
$MinecraftVersion = '26.2'
$FabricLoaderVersion = '0.19.3'
$JavaMinimum = 25

function Write-Step([string]$Message) {
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Assert-Command([string]$CommandName) {
    if (-not (Get-Command $CommandName -ErrorAction SilentlyContinue)) {
        throw "Required command '$CommandName' was not found. Install Java $JavaMinimum (64-bit), then reopen this window."
    }
}

function Assert-JavaVersion {
    $VersionText = (& java -version 2>&1 | Out-String)
    Write-Host $VersionText.Trim()
    $Match = [regex]::Match($VersionText, 'version "(?<major>\d+)')
    if (-not $Match.Success) {
        throw 'Could not determine the Java version from java -version.'
    }
    $Major = [int]$Match.Groups['major'].Value
    if ($Major -lt $JavaMinimum) {
        throw "Java $JavaMinimum or newer is required for this Minecraft 26.2 setup. Detected Java $Major."
    }
}

function Get-Sha512([string]$Path) {
    return (Get-FileHash -Algorithm SHA512 -LiteralPath $Path).Hash.ToLowerInvariant()
}

function Download-AndVerify([string]$Url, [string]$Path, [string]$ExpectedSha512) {
    $Headers = @{ 'User-Agent' = 'Jarock-Fabric-Bootstrap/0.0.1-alpha (https://github.com/PiBOH/jarock)' }
    if (-not (Test-Path -LiteralPath $Path)) {
        Write-Host "Downloading $([IO.Path]::GetFileName($Path)) ..."
        Invoke-WebRequest -Uri $Url -OutFile $Path -Headers $Headers -UseBasicParsing
    }

    $Actual = Get-Sha512 $Path
    if ($Actual -ne $ExpectedSha512.ToLowerInvariant()) {
        Remove-Item -LiteralPath $Path -Force
        throw "SHA-512 verification failed for $Path. The file was removed."
    }
}

function Ensure-EulaTemplate {
    $EulaPath = Join-Path $ServerDir 'eula.txt'
    $TemplatePath = Join-Path $ServerDir 'eula.txt.template'
    if (-not (Test-Path -LiteralPath $EulaPath) -and (Test-Path -LiteralPath $TemplatePath)) {
        Copy-Item -LiteralPath $TemplatePath -Destination $EulaPath
    }
}

Write-Step 'Checking prerequisites'
Assert-Command 'java'
Assert-JavaVersion

New-Item -ItemType Directory -Force -Path $ServerDir, $ModsDir | Out-Null
if (-not (Test-Path -LiteralPath $ManifestPath)) {
    throw "Missing mod manifest: $ManifestPath"
}
. $ManifestPath

Write-Step 'Downloading and verifying the official Fabric installer'
Download-AndVerify $FabricInstallerUrl $FabricInstaller $FabricInstallerSha512

if (-not (Test-Path -LiteralPath (Join-Path $ServerDir 'fabric-server-launch.jar'))) {
    Write-Step "Installing Fabric Server for Minecraft $MinecraftVersion (Loader $FabricLoaderVersion)"
    Push-Location $ServerDir
    try {
        & java -jar $FabricInstaller server -mcversion $MinecraftVersion -loader $FabricLoaderVersion -downloadMinecraft
        if ($LASTEXITCODE -ne 0) { throw "Fabric installer exited with code $LASTEXITCODE." }
    }
    finally {
        Pop-Location
    }
}

Write-Step 'Downloading and verifying pinned server mods'
foreach ($Mod in $Mods) {
    $Destination = Join-Path $ModsDir $Mod.Name
    Download-AndVerify $Mod.Url $Destination $Mod.Sha512
    Write-Host "Verified $($Mod.Name) [$($Mod.Purpose)]" -ForegroundColor Green
}

Ensure-EulaTemplate

$PropertiesPath = Join-Path $ServerDir 'server.properties'
$PropertiesTemplate = Join-Path $ServerDir 'server.properties.template'
if (-not (Test-Path -LiteralPath $PropertiesPath) -and (Test-Path -LiteralPath $PropertiesTemplate)) {
    Copy-Item -LiteralPath $PropertiesTemplate -Destination $PropertiesPath
    Write-Host 'Created server.properties from the safe template.' -ForegroundColor Green
}

Write-Step 'Bootstrap complete'
Write-Host 'No router, firewall, port-forwarding, or public-network changes were performed.' -ForegroundColor Yellow
Write-Host 'Geyser configuration is generated by the first server start; the start script applies auth-type: floodgate afterward.'
Write-Host 'If eula=true is accepted, start-server.bat will launch the server.'
